{% set name = "sci-fab" %}
{% set version = "2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2e38f03c97702af8136cadf5c03c9b0903efd9f4456952c2eeac6a3f7bf55a6a

build:
  number: 0
  noarch: python
  entry_points:
    - fab=fab.cli:cli_fab
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - fparser
    - python >={{ python_min }},<4.0

test:
  imports:
    - fab
    - fab.parse
  commands:
    - pip check
    - fab --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Metomi/fab
  summary: Build system for scientific software
  dev_url: https://github.com/metomi/fab/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GiorgiaLine
    - MatthewHambley
