{% set name = "sci-fab" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sci-fab-{{ version }}.tar.gz
  sha256: 787dd4bc55e7910706c5c1a615d2dbf38d93d697aacf8f9b336644a050f3126f

build:
  number: 0
  noarch: python
  entry_points:
    - fab=fab.cli:cli_fab
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - fparser
    - python >=3.6,<4.0

test:
  imports:
    - fab
    - fab.parse
  commands:
    - pip check
    - fab --help
  requires:
    - pip

about:
  home: https://github.com/Metomi/fab
  summary: Build system for scientific software
  dev_url: https://github.com/metomi/fab/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GiorgiaLine
    - MatthewHambley
